plugins:
  - angular

env:
  node: false

globals:
  angular: true

rules:
  angular/angularelement: 2
  angular/component-limit:
    - 2
    - 1
  angular/controller-as: 2
  angular/controller-as-route: 2
  angular/controller-as-vm:
    - 2
    - vm
  angular/controller-name:
    - 2
    - /[A-Z][a-zA-Z]*Controller$/
  angular/deferred: 2
  angular/definedundefined: 0
  angular/di:
    - 2
    - function
  angular/di-order: 2
  angular/di-unused: 2
  angular/directive-name:
    - 2
    - nn
  angular/directive-restrict:
    - 2
    - explicit: never
  angular/document-service: 2
  angular/empty-controller: 2
  angular/filter-name: 2
  angular/foreach: 0
  angular/function-type:
    - 2
    - named
  angular/interval-service: 2
  angular/json-functions: 2
  angular/log: 0
  angular/module-dependency-order:
    - 2
    - prefix: app
  angular/module-getter: 2
  angular/module-name:
    - 2
    - app
  angular/module-setter: 2
  angular/no-angular-mock: 2
  angular/no-controller: 0
  angular/no-cookiestore: 2
  angular/no-digest: 2
  angular/no-http-callback: 2
  angular/no-inline-template:
    - 2
    - allowSimple: true
  angular/no-jquery-angularelement: 2
  angular/no-private-call: 2
  angular/no-service-method: 2
  angular/no-services: 2
  angular/on-watch: 2
  angular/service-name: 2
  angular/timeout-service: 2
  angular/typecheck-array: 0
  angular/typecheck-boolean: 0
  angular/typecheck-date: 0
  angular/typecheck-function: 0
  angular/typecheck-number: 0
  angular/typecheck-object: 0
  angular/typecheck-regexp: 0
  angular/typecheck-string: 0
  angular/watchers-execution: 0
  angular/window-service: 2
